feat: Move duration for poll into config file
SeedyROM/croncat-rs pull request #66
Opened 2022-09-28 02:32 UTC by deveusss

Closes #63

2022-09-28 04:39 UTC, SeedyROM requested changes
See note about setting up the git hooks so you aren't commiting unformatted code.

2022-09-28 04:39 UTC, SeedyROM commented on croncat/src/config/mod.rs
> +    pub polling_duration_secs:u64,
Could you follow the instructions in the README on how to setup the git hooks so we don't push unformatted code.

2022-09-28 04:39 UTC, SeedyROM commented on croncat/src/system/mod.rs
> +    polling_duration_secs:u64,
Same here.

2022-09-28 04:39 UTC, SeedyROM commented on croncatd/src/main.rs
> +            system::run(shutdown_tx,
Yeah same here too.

2022-09-28 21:13 UTC, deveusss commented on croncat/src/system/mod.rs
> +    polling_duration_secs:u64,
thank you)

2022-09-28 21:28 UTC, SeedyROM approved these changes
LGTM! :hammer_and_pick:

2022-10-03 18:31 UTC, TrevorJTClarke approved these changes
Very much needed, thank you!

2022-10-03 22:21 UTC, merged